#!/bin/sh

# Available devices
all_devices=`find /dev/disk/by-id | grep -v '\-part' | grep '\/ata-'`
devices=`hddtemp $all_devices 2> /dev/null | grep ': [0-9]\+°C' | cut -d: -f 1 `

exec /usr/bin/hddtemp -dF $devices
